<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="hello.services.ThingServicesSpec" tests="5" skipped="0" failures="0" errors="0" timestamp="2019-06-06T20:44:18" hostname="yuliban" time="0.429">
  <properties/>
  <testcase name="failSavingThingInMock" classname="hello.services.ThingServicesSpec" time="0.411"/>
  <testcase name="getThingFromH2" classname="hello.services.ThingServicesSpec" time="0.009"/>
  <testcase name="saveThing" classname="hello.services.ThingServicesSpec" time="0.003"/>
  <testcase name="getNoneFromH2" classname="hello.services.ThingServicesSpec" time="0.002"/>
  <testcase name="getThingFromMock" classname="hello.services.ThingServicesSpec" time="0.002"/>
  <system-out><![CDATA[Completion exception hello.domain.errors.ThingAlreadyExist
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
